package codec

func Table() []Codec {
	return []Codec{
		{Name: "zip", Extensions: []string{".zip"}, Kind: KindArchive, Bin: "zip", BrewFormula: "",
			CreateArgs: []string{"-r", "{level}", "{out}", "{in}"},
			AddArgs:    []string{"{out}", "{in}"}, DeleteArgs: []string{"-d", "{out}", "{member}"},
			TestArgs: []string{"-T", "{out}"}, ListArgs: []string{"-sf", "{out}"},
			ExtractBin: "unzip", ExtractArgs: []string{"-o", "{out}", "-d", "{dest}"}, Fast: "-1", Normal: "-6", Max: "-9"},
		{Name: "7z", Extensions: []string{".7z"}, Kind: KindArchive, Bin: "7z", BrewFormula: "sevenzip",
			CreateArgs: []string{"a", "{level}", "{out}", "{in}"},
			AddArgs:    []string{"u", "{out}", "{in}"}, DeleteArgs: []string{"d", "{out}", "{member}"},
			TestArgs: []string{"t", "{out}"}, ListArgs: []string{"l", "{out}"},
			ExtractArgs: []string{"x", "{out}", "-o{dest}", "-y"}, Fast: "-mx1", Normal: "-mx5", Max: "-mx9"},
		{Name: "tar", Extensions: []string{".tar"}, Kind: KindArchive, Bin: "tar", BrewFormula: "",
			CreateArgs: []string{"-cf", "{out}", "-C", "{indir}", "{inbase}"},
			AddArgs:    []string{"-rf", "{out}", "-C", "{indir}", "{inbase}"},
			DeleteArgs: []string{},
			TestArgs:   []string{"-tf", "{out}"}, ListArgs: []string{"-tf", "{out}"},
			ExtractArgs: []string{"-xf", "{out}", "-C", "{dest}"}},
		{Name: "rar", Extensions: []string{".rar"}, Kind: KindArchive, Bin: "rar", BrewFormula: "rar",
			CreateArgs: []string{"a", "{level}", "{out}", "{in}"},
			AddArgs:    []string{"u", "{out}", "{in}"},
			TestArgs:   []string{"t", "{out}"}, ListArgs: []string{"l", "{out}"},
			Fast: "-m1", Normal: "-m3", Max: "-m5"},
		{Name: "zpaq", Extensions: []string{".zpaq"}, Kind: KindArchive, Bin: "zpaq", BrewFormula: "zpaq",
			CreateArgs: []string{"add", "{out}", "{in}", "-{level}"},
			AddArgs:    []string{"add", "{out}", "{in}"},
			TestArgs:   []string{"x", "{out}", "-test"},
			ListArgs:   []string{"l", "{out}"}, Fast: "1", Normal: "5", Max: "9"},
		{Name: "aar", Extensions: []string{".aar"}, Kind: KindArchive, Bin: "aar", BrewFormula: "",
			CreateArgs: []string{"c", "{out}", "{in}"},
			TestArgs:   []string{"t", "{out}"}, ListArgs: []string{"l", "{out}"}},
		{Name: "gzip", Extensions: []string{".gz", ".tgz"}, Kind: KindStream, Bin: "gzip", BrewFormula: "",
			CreateArgs: []string{"-{level}", "-k", "-f", "{in}"}, Fast: "1", Normal: "6", Max: "9"},
		{Name: "bzip2", Extensions: []string{".bz2", ".tbz2"}, Kind: KindStream, Bin: "bzip2", BrewFormula: "",
			CreateArgs: []string{"-{level}", "-k", "-f", "{in}"}, Fast: "1", Normal: "9", Max: "9"},
		{Name: "xz", Extensions: []string{".xz", ".txz"}, Kind: KindStream, Bin: "xz", BrewFormula: "xz",
			CreateArgs: []string{"-{level}", "-T0", "-k", "-f", "{in}"}, Fast: "1", Normal: "6", Max: "9"},
		{Name: "lzip", Extensions: []string{".lz"}, Kind: KindStream, Bin: "lzip", BrewFormula: "lzip",
			CreateArgs: []string{"-{level}", "-k", "-f", "{in}"}, Fast: "1", Normal: "6", Max: "9"},
		{Name: "lzma", Extensions: []string{".lzma"}, Kind: KindStream, Bin: "lzma", BrewFormula: "xz",
			CreateArgs: []string{"-{level}", "-k", "-f", "{in}"}, Fast: "1", Normal: "6", Max: "9"},
		{Name: "zstd", Extensions: []string{".zst", ".tzst"}, Kind: KindStream, Bin: "zstd", BrewFormula: "zstd",
			CreateArgs: []string{"-{level}", "-T4", "-k", "-f", "{in}"}, Fast: "fast3", Normal: "19", Max: "22"},
		{Name: "lz4", Extensions: []string{".lz4"}, Kind: KindStream, Bin: "lz4", BrewFormula: "lz4",
			CreateArgs: []string{"-{level}", "-f", "{in}", "{out}"}, Fast: "1", Normal: "6", Max: "12"},
		{Name: "brotli", Extensions: []string{".br"}, Kind: KindStream, Bin: "brotli", BrewFormula: "brotli",
			CreateArgs: []string{"-{level}", "-k", "-f", "{in}"}, Fast: "1", Normal: "9", Max: "11"},
		{Name: "lzo", Extensions: []string{".lzo"}, Kind: KindStream, Bin: "lzop", BrewFormula: "lzop",
			CreateArgs: []string{"-{level}", "-fU", "{in}"}, Fast: "1", Normal: "6", Max: "9"},
		{Name: "snappy", Extensions: []string{".sz"}, Kind: KindStream, Bin: "snzip", BrewFormula: "snzip",
			CreateArgs: []string{"-f", "-o", "{out}", "{in}"}},
		{Name: "lrzip", Extensions: []string{".lrz"}, Kind: KindStream, Bin: "lrzip", BrewFormula: "lrzip",
			CreateArgs: []string{"-{level}", "-f", "{in}"}, Fast: "1", Normal: "7", Max: "9"},
	}
}
